---
title: "MAGMA visualization"
output: html_notebook
---

## Functions used for this visualization

### Function to clean data

```{r}
removeSwappedDupKeyValueDf <- function(x){
  foo <- igraph::graph_from_data_frame(x,directed=FALSE)
  foo <- igraph::simplify(foo,edge.attr.comb = list("first"))
  foo <- igraph::as_data_frame(foo,what='edges')
  return(foo)
}

```

### Plotting a graph given labels for nodes (and node sizes)

```{r}
PlotGraphGivenLabels <- function(Net,l,Labels, SizeList = c(), 
                                 LegendNames = c(), 
                                 sizeMin = 3, sizeMax = 10, 
                                 VertName = c()){
  
  cmap <- rainbow(max(Labels), alpha=1)
  for( i in 1:max(Labels)){
    cat('No. of modules in cluster',i,'is =',
        sum(Labels==i),'\n')
  }  
  
  V(Net)$color <- cmap[Labels]
  if (length(SizeList)>0){
    V(Net)$size <- sizeMin + SizeList/max(SizeList)*sizeMax
  }

  #generating the plot 
  print('Generating the plot')
  #plot(Net, edge.arrow.size=.4,vertex.label=NA,
  #    layout=layout_with_fr(Net, niter = 5000, grid = 'nogrid'))
  
  
  #adding legend 
  if (length(LegendNames)==0){
    LegendNames <- c(1:max(Labels)) 
  }
  if (length(VertName)==0){
    plot(Net, edge.arrow.size=.4,vertex.label=NA, layout = l)
    legend(x=-1.5, y=-1.1,LegendNames,pch=21,col="#777777", pt.bg=cmap,
           pt.cex=2, cex=.8, bty="n", ncol=5)
  } else {
    Net$label <- VertName
    plot(Net, edge.arrow.size=.4, layout = l,
         vertex.label = VertName,  
         vertex.label.color = 'black',
         vertex.label.cex = 0.6, vertex.label.font = 2)
    legend(x=-1.5, y=-1.1,LegendNames,pch=21,col="#777777", pt.bg=cmap,
           pt.cex=2, cex=.8, bty="n", ncol=5)
  }
  
  return(Net)  
  
}
```

### Creating graph layout
```{r}
GenGraphViz <- function(x, pattern, Types,
                        sizeMin = 3, sizeMax = 10){
  
  #identifying subset of data to use
  print('Obtaining sub-graph based on brain region')
  In1 <- grep(pattern,Dat$from)
  In2 <- grep(pattern,Dat$to)
  In_int <- intersect(In1,In2)
  Dat <- Dat[In_int,]
  
  #annotating nodes by algorithm type
  print('Annotating nodes by algorithm type')
  ModNames <- c()
  ModType <- c()
  TypeName <- c()
  
  l <- length(Types)
  
  for (i in 1:l){
    temp <- union(grep(Types[i],Dat$from, value= TRUE),
                  grep(Types[i],Dat$to, value= TRUE))
    ModNames <- c(ModNames,temp)
    ModType <- c(ModType,rep(i,length(temp)))
    cat('No. of modules in',Types[i],length(temp),'\n')
    TypeName <- c(TypeName, rep(Types[i],length(temp)))
  }
  
  #creating visualization 
  print('Creating visualization')
  df <- data.frame(Name = ModNames, ModType = ModType, 
                   TypeName = TypeName)
  library('igraph')
  df2 <- data.frame(from = Dat$from, 
                    to = Dat$to,
                    weight =  1/(1e-50 + c(Dat$fisherOR)^1))
  net <- graph.data.frame(df2, vertices=df, directed=F) 
  
  #coloring nodes on the basis of module type 
  cmap <- rainbow(l, alpha=1) 
  V(net)$color <- cmap[V(net)$ModType]
  deg <- 1/(1e-50 + strength(net))
  V(net)$size <- sizeMin + deg/max(deg)*sizeMax
  #l <- layout_with_fr(net, niter = 5000, grid = 'nogrid')
  l <- layout_with_graphopt(net, niter= 500, charge = 0.01, mass = .0001,
                             spring.constant = 10)
  E(net)$width <- 1*(E(net)$weight - min(E(net)$weight))/max(E(net)$weight)
  #E(net)$width[E(net)$width <= median(E(net)$weight)] <- 0
  m <- median(E(net)$weight)
  net <- delete_edges(net, E(net)[weight<m])

  #l <- layout_with_kk(net)
  

  #returning igraph object and layout
  RetDat <- list()
  RetDat$net <- net 
  RetDat$l <- l 
  return(RetDat)
  
  
}
```


# Main program 

### Log into Synapse

```{r}
#synapseClient::synapseLogin()

```

### Downloading network modules and pairwise scores

```{r}
Dat <- synapseClient::synTableQuery("SELECT * FROM syn10339153 where ModuleNameFull like '%DLPFC' and category like '%DLPFC'")@values
Dat <- removeSwappedDupKeyValueDf(Dat)
Dat <- dplyr::mutate(Dat,adj=p.adjust(fisherPval,method='fdr'))
Dat <- dplyr::filter(Dat,adj<=0.05)
#Drop rows with infinite fisherOR
In <- which(Dat$fisherOR==Inf)
Dat <- Dat[-In, ]
m <- median(Dat$fisherOR) #keeping only top half of significant interactions
In <- which(Dat$fisherOR<m)
Dat <- Dat[-In, ]
```

### Generating network layout

```{r}
pattern <- "DLPFC"
Types <- c('consensus','megena','metanetwork','rWGCNA','speakEasy','wina')
RetGraph <- GenGraphViz(Dat,pattern, Types)
Net <- RetGraph$net 
lt <- RetGraph$l 
```

### Downloading MAGMA enrichment scores 

```{r}

M_score <- synapseClient::synTableQuery("SELECT * FROM syn10380432 WHERE 
                                        brainRegion = 'DLPFC'")@values
```

### Generating visualization with MAGMA enrichment as node sizes

```{r}

m <- min(-log10(M_score$P))
NoNodes <- length(names(V(Net)))
SizeList <- rep(m,NoNodes)
Labels <- rep('consensus',NoNodes)
#Identify modules which don't have corresponding nodes
In <- which(M_score$SET %in% names(V(Net)))
M_score <- M_score[In,]
#Identify mapping of modules to nodes
In <- c()
for (i in 1:length(M_score$SET)){
  In <- c(In, which(names(V(Net)) == M_score$SET[i]))
}
SizeList[In] <- -log10(M_score$P)
Labels[In] <- M_score$method
Labels2 <- rep(0,length(Labels))
for (i in 1:length(Labels)){
  Labels2[i] <- which(Types %in% Labels[i])
}

Net2 <- PlotGraphGivenLabels(Net, lt, Labels2, SizeList, LegendNames = Types )

```

